swagger: '2.0'
info:
  description: A Property Search API
  title: search-radius
  version: v1
host: api.ipify.org
schemes:
  - https
basePath: /search
paths:
  /getProperties:
    get:
      summary: Get Properties List
      parameters:
        - in: query
          name: price
          type: string
          description: 'The price to return the response in, i.e. json.'
          default: json
      responses:
        '200':
          description: Success response
          schema:
            type: object
            properties:
              ip:
                type: string
                example: Rs.3000          